// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientAccounts.proto

package com.lykke.client.accounts.incoming;

public final class ClientAccountMessages {
  private ClientAccountMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WalletCreatedEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lykke.client.accounts.incoming.WalletCreatedEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string clientId = 1;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>string clientId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string walletId = 2;</code>
     */
    java.lang.String getWalletId();
    /**
     * <code>string walletId = 2;</code>
     */
    com.google.protobuf.ByteString
        getWalletIdBytes();

    /**
     * <code>string walletType = 3;</code>
     */
    java.lang.String getWalletType();
    /**
     * <code>string walletType = 3;</code>
     */
    com.google.protobuf.ByteString
        getWalletTypeBytes();
  }
  /**
   * Protobuf type {@code com.lykke.client.accounts.incoming.WalletCreatedEvent}
   */
  public  static final class WalletCreatedEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lykke.client.accounts.incoming.WalletCreatedEvent)
      WalletCreatedEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WalletCreatedEvent.newBuilder() to construct.
    private WalletCreatedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WalletCreatedEvent() {
      clientId_ = "";
      walletId_ = "";
      walletType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WalletCreatedEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              walletId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              walletType_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lykke.client.accounts.incoming.ClientAccountMessages.internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lykke.client.accounts.incoming.ClientAccountMessages.internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent.class, com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string clientId = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WALLETID_FIELD_NUMBER = 2;
    private volatile java.lang.Object walletId_;
    /**
     * <code>string walletId = 2;</code>
     */
    public java.lang.String getWalletId() {
      java.lang.Object ref = walletId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        walletId_ = s;
        return s;
      }
    }
    /**
     * <code>string walletId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWalletIdBytes() {
      java.lang.Object ref = walletId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        walletId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WALLETTYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object walletType_;
    /**
     * <code>string walletType = 3;</code>
     */
    public java.lang.String getWalletType() {
      java.lang.Object ref = walletType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        walletType_ = s;
        return s;
      }
    }
    /**
     * <code>string walletType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWalletTypeBytes() {
      java.lang.Object ref = walletType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        walletType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getWalletIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, walletId_);
      }
      if (!getWalletTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, walletType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getWalletIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, walletId_);
      }
      if (!getWalletTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, walletType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent)) {
        return super.equals(obj);
      }
      com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent other = (com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getWalletId()
          .equals(other.getWalletId());
      result = result && getWalletType()
          .equals(other.getWalletType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + WALLETID_FIELD_NUMBER;
      hash = (53 * hash) + getWalletId().hashCode();
      hash = (37 * hash) + WALLETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getWalletType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lykke.client.accounts.incoming.WalletCreatedEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lykke.client.accounts.incoming.WalletCreatedEvent)
        com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lykke.client.accounts.incoming.ClientAccountMessages.internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lykke.client.accounts.incoming.ClientAccountMessages.internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent.class, com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent.Builder.class);
      }

      // Construct using com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientId_ = "";

        walletId_ = "";

        walletType_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lykke.client.accounts.incoming.ClientAccountMessages.internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_descriptor;
      }

      @java.lang.Override
      public com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent getDefaultInstanceForType() {
        return com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent build() {
        com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent buildPartial() {
        com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent result = new com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent(this);
        result.clientId_ = clientId_;
        result.walletId_ = walletId_;
        result.walletType_ = walletType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent) {
          return mergeFrom((com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent other) {
        if (other == com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getWalletId().isEmpty()) {
          walletId_ = other.walletId_;
          onChanged();
        }
        if (!other.getWalletType().isEmpty()) {
          walletType_ = other.walletType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string clientId = 1;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object walletId_ = "";
      /**
       * <code>string walletId = 2;</code>
       */
      public java.lang.String getWalletId() {
        java.lang.Object ref = walletId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          walletId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string walletId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWalletIdBytes() {
        java.lang.Object ref = walletId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          walletId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string walletId = 2;</code>
       */
      public Builder setWalletId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        walletId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string walletId = 2;</code>
       */
      public Builder clearWalletId() {
        
        walletId_ = getDefaultInstance().getWalletId();
        onChanged();
        return this;
      }
      /**
       * <code>string walletId = 2;</code>
       */
      public Builder setWalletIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        walletId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object walletType_ = "";
      /**
       * <code>string walletType = 3;</code>
       */
      public java.lang.String getWalletType() {
        java.lang.Object ref = walletType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          walletType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string walletType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getWalletTypeBytes() {
        java.lang.Object ref = walletType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          walletType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string walletType = 3;</code>
       */
      public Builder setWalletType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        walletType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string walletType = 3;</code>
       */
      public Builder clearWalletType() {
        
        walletType_ = getDefaultInstance().getWalletType();
        onChanged();
        return this;
      }
      /**
       * <code>string walletType = 3;</code>
       */
      public Builder setWalletTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        walletType_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lykke.client.accounts.incoming.WalletCreatedEvent)
    }

    // @@protoc_insertion_point(class_scope:com.lykke.client.accounts.incoming.WalletCreatedEvent)
    private static final com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent();
    }

    public static com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WalletCreatedEvent>
        PARSER = new com.google.protobuf.AbstractParser<WalletCreatedEvent>() {
      @java.lang.Override
      public WalletCreatedEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WalletCreatedEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WalletCreatedEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WalletCreatedEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lykke.client.accounts.incoming.ClientAccountMessages.WalletCreatedEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ClientAccounts.proto\022\"com.lykke.client" +
      ".accounts.incoming\"L\n\022WalletCreatedEvent" +
      "\022\020\n\010clientId\030\001 \001(\t\022\020\n\010walletId\030\002 \001(\t\022\022\n\n" +
      "walletType\030\003 \001(\tB;\n\"com.lykke.client.acc" +
      "ounts.incomingB\025ClientAccountMessagesb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lykke_client_accounts_incoming_WalletCreatedEvent_descriptor,
        new java.lang.String[] { "ClientId", "WalletId", "WalletType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
